---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-1
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-1
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-1"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-2
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-2
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-2"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-3
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-3
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-3"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-4
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-4
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-4"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-5
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-5
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-5"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-6
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-6
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-6"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-7
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-7
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-7"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-8
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-8
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-8"}' > /var/www/health/index.html
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-9
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/size: tiny
        kubevirt.io/domain: vm-9
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 32M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: 1234
              chpasswd: { expire: False }
              ssh_pwauth: True
              runcmd:
                - mkdir -p /var/www/health
                - echo '{"status":"healthy","id":"vm-9"}' > /var/www/health/index.html
