apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-flask-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    # Scale based on CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10   # Very low threshold for easy testing
    # Scale based on Memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 15   # Very low threshold for easy testing
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10   # Scale up quickly
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 30   # Wait before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
