apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-flask-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # Scale based on CPU utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    # Scale based on Memory utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80   # Scale when memory exceeds 80% of request
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10   # Scale up quickly
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 10  # Wait 10 second before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30            # Scale down 30 seconds
