apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  to:
    kind: Service
    name: simple-flask-app
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
